version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "gaganpreet"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/client"
    assignees:
      - "gaganpreet"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/backend"
    assignees:
      - "gaganpreet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/backend/app/"
    assignees:
      - "gaganpreet"
    schedule:
      interval: "daily"
