"""add location models

Revision ID: 00146b400b05
Revises: 35c94a4f3c64
Create Date: 2020-11-14 23:51:47.913989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00146b400b05'
down_revision = '35c94a4f3c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ip_city_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('ip_continent_code', sa.String(length=2), nullable=True))
    op.add_column('event', sa.Column('ip_country_iso_code', sa.String(length=2), nullable=True))
    op.add_column('event', sa.Column('ip_timezone', sa.String(), nullable=True))
    op.create_foreign_key('fk_event_country_id', 'event', 'country', ['ip_country_iso_code'], ['id'])
    op.create_foreign_key('fk_event_city_id', 'event', 'city', ['ip_city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_city_id', 'event', type_='foreignkey')
    op.drop_constraint('fk_event_country_id', 'event', type_='foreignkey')
    op.drop_column('event', 'ip_timezone')
    op.drop_column('event', 'ip_country_iso_code')
    op.drop_column('event', 'ip_continent_code')
    op.drop_column('event', 'ip_city_id')
    # ### end Alembic commands ###
