"""add device_type column

Revision ID: 184d636be565
Revises: eb48b4fcc2ec
Create Date: 2021-07-14 19:09:53.760941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184d636be565'
down_revision = 'eb48b4fcc2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('device_type', sa.Enum('mobile', 'desktop', 'tablet', name='devicetype', native_enum=False), nullable=True))
    op.create_index('ix_bot', 'event', ['domain_id', 'is_bot', 'timestamp'], unique=False)
    op.create_index('ix_device_type', 'event', ['domain_id', 'device_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_type', table_name='event')
    op.drop_index('ix_bot', table_name='event')
    op.drop_column('event', 'device_type')
    # ### end Alembic commands ###
