"""add columns for time values

Revision ID: 1fbed1fd8b9d
Revises: 6ac3ac0be773
Create Date: 2020-09-19 20:51:56.788626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbed1fd8b9d'
down_revision = '6ac3ac0be773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('dnslookup_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('download_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('fetch_time', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('time_to_first_byte', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('total_time', sa.Integer(), nullable=True))
    op.drop_column('event', 'load_time_ms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('load_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('event', 'total_time')
    op.drop_column('event', 'time_to_first_byte')
    op.drop_column('event', 'fetch_time')
    op.drop_column('event', 'download_time')
    op.drop_column('event', 'dnslookup_time')
    # ### end Alembic commands ###
