"""remove visitor model

Revision ID: 218c88086610
Revises: e748644a1d21
Create Date: 2020-08-30 20:59:59.789495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '218c88086610'
down_revision = 'e748644a1d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_visitor_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'visitor_id')
    op.drop_index('ix_visitor_id', table_name='visitor')
    op.drop_table('visitor')
    op.add_column('event', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('event', sa.Column('uid', sa.String(), nullable=True))
    op.create_foreign_key('fk_event_domain_id', 'event', 'domain', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('visitor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_event_domain_id', 'event', type_='foreignkey')
    op.create_foreign_key('event_visitor_id_fkey', 'event', 'visitor', ['visitor_id'], ['id'])
    op.drop_column('event', 'uid')
    op.drop_column('event', 'raw_data')
    op.drop_column('event', 'domain_id')
    op.create_table('visitor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name='visitor_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='visitor_pkey')
    )
    op.create_index('ix_visitor_id', 'visitor', ['id'], unique=False)
    # ### end Alembic commands ###
