"""Add index on location

Revision ID: 2b4a9f1ddb57
Revises: 2dd6c012251f
Create Date: 2020-12-16 15:08:18.836082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4a9f1ddb57'
down_revision = '2dd6c012251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_custom_metric', 'event', ['domain_id', 'metric_name', 'timestamp'], unique=False)
    op.create_index('ix_location', 'event', ['domain_id', 'ip_country_iso_code', 'ip_city_id', 'timestamp'], unique=False)
    op.drop_index('ix_os_family', table_name='event')
    op.create_index('ix_os_family', 'event', ['domain_id', 'os_family', 'os_version_major', 'os_version_minor', 'timestamp'], unique=False)
    op.drop_index('ix_device_metric', table_name='event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_device_metric', 'event', ['domain_id', 'metric_name', 'timestamp'], unique=False)
    op.drop_index('ix_os_family', table_name='event')
    op.create_index('ix_os_family', 'event', ['domain_id', 'os_family', 'timestamp'], unique=False)
    op.drop_index('ix_location', table_name='event')
    op.drop_index('ix_custom_metric', table_name='event')
    # ### end Alembic commands ###
