"""remove ip address column

Revision ID: 2ff711f69dde
Revises: e55f4d11ba60
Create Date: 2021-03-16 19:27:35.984064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff711f69dde'
down_revision = 'e55f4d11ba60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'ip_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
