"""add parsed ua column

Revision ID: 35c94a4f3c64
Revises: 4016d624841c
Create Date: 2020-10-21 10:57:42.316251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35c94a4f3c64'
down_revision = '4016d624841c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('parsed_ua', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'parsed_ua')
    # ### end Alembic commands ###
