"""update some columns, use numeric types

Revision ID: 4016d624841c
Revises: 1fbed1fd8b9d
Create Date: 2020-10-11 13:47:42.863965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4016d624841c'
down_revision = '1fbed1fd8b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('event', 'download_time',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('event', 'time_to_first_byte',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('event', 'total_time',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('event', 'raw_data')
    op.drop_column('event', 'status_code')
    op.drop_column('event', 'uid')
    op.drop_column('event', 'fetch_time')
    op.drop_column('event', 'dnslookup_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('dnslookup_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('fetch_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('event', 'total_time',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('event', 'time_to_first_byte',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('event', 'download_time',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('event', 'url')
    op.drop_column('event', 'ip_address')
    # ### end Alembic commands ###
