"""Create migration to remove event timestamp index

Revision ID: 436ff473b7a6
Revises: 93c03921e60f
Create Date: 2020-12-11 19:22:31.991484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436ff473b7a6'
down_revision = '93c03921e60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('event_timestamp_idx', table_name='event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('event_timestamp_idx', 'event', ['timestamp'], unique=False)
    # ### end Alembic commands ###
