"""update trial interval

Revision ID: 43a06710fa6d
Revises: 42e19a87d094
Create Date: 2021-07-29 16:25:58.212553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a06710fa6d'
down_revision = '42e19a87d094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'device_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('mobile', 'desktop', 'tablet', name='devicetype', native_enum=False, length=50),
               existing_nullable=True)
    op.alter_column(
        "user",
        "trial_end_date",
        server_default=sa.text("NOW() + ('30 days')::interval"),
    )
    op.alter_column('user', 'active_plan',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('no_plan', 'trial_expired', 'free', 'lite', 'medium', 'enterprise', 'cancelled', name='plan', native_enum=False, length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active_plan',
               existing_type=sa.Enum('no_plan', 'trial_expired', 'free', 'lite', 'medium', 'enterprise', 'cancelled', name='plan', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column(
        "user",
        "trial_end_date",
        server_default=sa.text("NOW() + ('14 days')::interval"),
    )
    op.alter_column('event', 'device_type',
               existing_type=sa.Enum('mobile', 'desktop', 'tablet', name='devicetype', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
