"""remove unused fields from event data

Revision ID: 60d6fb1b4bda
Revises: f4d14f0221ec
Create Date: 2021-05-22 13:41:37.142725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d6fb1b4bda'
down_revision = 'f4d14f0221ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_city_id', 'event', type_='foreignkey')
    op.drop_index('ix_device_family', table_name='event')
    op.drop_index('ix_device_model', table_name='event')
    op.drop_index('ix_location', table_name='event')
    op.create_index('ix_location', 'event', ['domain_id', 'ip_country_iso_code', 'timestamp'], unique=False)
    op.drop_index('ix_os_family', table_name='event')
    op.create_index('ix_os_family', 'event', ['domain_id', 'os_family', 'timestamp'], unique=False)
    op.create_index('id_path', 'event', ['domain_id', 'path', 'timestamp'], unique=False)

    op.drop_column('event', 'ip_city_id')
    op.drop_column('event', 'total_time')
    op.drop_column('event', 'time_to_first_byte')
    op.drop_column('event', 'page_title')
    op.drop_column('event', 'referrer')
    op.drop_column('event', 'device_model')
    op.drop_column('event', 'os_version_minor')
    op.drop_column('event', 'download_time')
    op.drop_column('event', 'url')
    op.drop_column('event', 'ua_string')
    op.drop_column('event', 'device_family')
    op.drop_column('event', 'page_size_bytes')
    op.drop_column('event', 'user_timezone_offset')
    op.drop_column('event', 'ip_timezone')
    op.drop_column('event', 'browser_version_minor')
    op.drop_column('event', 'os_version_major')
    op.drop_table('city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asciiname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='fk_event_country_id'),
    sa.PrimaryKeyConstraint('id', name='city_pkey')
    )
    op.drop_index('id_path', table_name='event')
    op.drop_index('ix_os_family', table_name='event')
    op.drop_index('ix_location', table_name='event')
    op.add_column('event', sa.Column('os_version_major', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('browser_version_minor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('ip_timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('user_timezone_offset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('page_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('device_family', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('ua_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('download_time', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('os_version_minor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('device_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('page_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('time_to_first_byte', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('total_time', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('ip_city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_event_city_id', 'event', 'city', ['ip_city_id'], ['id'])
    op.create_index('ix_os_family', 'event', ['domain_id', 'os_family', 'os_version_major', 'os_version_minor', 'timestamp'], unique=False)
    op.create_index('ix_location', 'event', ['domain_id', 'ip_country_iso_code', 'ip_city_id', 'timestamp'], unique=False)
    op.create_index('ix_device_model', 'event', ['domain_id', 'device_model', 'timestamp'], unique=False)
    op.create_index('ix_device_family', 'event', ['domain_id', 'device_family', 'timestamp'], unique=False)
    # ### end Alembic commands ###
