"""Restore missed event migration

Revision ID: 78a6df7ee296
Revises: de29c6b685cc
Create Date: 2021-02-08 20:27:23.395889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a6df7ee296'
down_revision = 'de29c6b685cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('utm_campaign', sa.String(), nullable=True))
    op.add_column('event', sa.Column('utm_content', sa.String(), nullable=True))
    op.add_column('event', sa.Column('utm_medium', sa.String(), nullable=True))
    op.add_column('event', sa.Column('utm_source', sa.String(), nullable=True))
    op.add_column('event', sa.Column('utm_term', sa.String(), nullable=True))
    op.drop_index('ix_event_url_params', table_name='event')
    op.create_index('ix_utm_campaign', 'event', ['domain_id', 'utm_campaign', 'timestamp'], unique=False, postgresql_where=sa.text('utm_campaign IS NOT NULL'))
    op.create_index('ix_utm_content', 'event', ['domain_id', 'utm_content', 'timestamp'], unique=False, postgresql_where=sa.text('utm_content IS NOT NULL'))
    op.create_index('ix_utm_medium', 'event', ['domain_id', 'utm_medium', 'timestamp'], unique=False, postgresql_where=sa.text('utm_medium IS NOT NULL'))
    op.create_index('ix_utm_source', 'event', ['domain_id', 'utm_source', 'timestamp'], unique=False, postgresql_where=sa.text('utm_source IS NOT NULL'))
    op.create_index('ix_utm_term', 'event', ['domain_id', 'utm_term', 'timestamp'], unique=False, postgresql_where=sa.text('utm_term IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utm_term', table_name='event')
    op.drop_index('ix_utm_source', table_name='event')
    op.drop_index('ix_utm_medium', table_name='event')
    op.drop_index('ix_utm_content', table_name='event')
    op.drop_index('ix_utm_campaign', table_name='event')
    op.create_index('ix_event_url_params', 'event', ['url_params'], unique=False)
    op.drop_column('event', 'utm_term')
    op.drop_column('event', 'utm_source')
    op.drop_column('event', 'utm_medium')
    op.drop_column('event', 'utm_content')
    op.drop_column('event', 'utm_campaign')
    # ### end Alembic commands ###
