"""Add paid referrer type

Revision ID: 92dd7090e30e
Revises: 812fd3fe30c1
Create Date: 2022-01-19 20:07:39.356559

"""
from app.models.event import ReferrerMediumType
from alembic import op
import sqlalchemy as sa
from alembic_helpers import migrate_enum


# revision identifiers, used by Alembic.
revision = "92dd7090e30e"
down_revision = "812fd3fe30c1"
branch_labels = None
depends_on = None

new_enums = sorted(v.value for v in ReferrerMediumType)
old_enums = [v for v in new_enums if v != "paid"]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_enum(
        "event", "referrer_medium", "referrer_medium_type", old_enums, new_enums
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_enum(
        "event", "referrer_medium", "referrer_medium_type", new_enums, old_enums
    )
    # ### end Alembic commands ###
