"""Add page view id

Revision ID: 93c03921e60f
Revises: 73e1037ccac3
Create Date: 2020-11-28 22:35:11.969808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93c03921e60f'
down_revision = '73e1037ccac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_domain_name', table_name='domain')
    op.create_index(op.f('ix_domain_domain_name'), 'domain', ['domain_name'], unique=True)
    op.add_column('event', sa.Column('page_view_id', postgresql.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'page_view_id')
    op.drop_index(op.f('ix_domain_domain_name'), table_name='domain')
    op.create_index('ix_domain_domain_name', 'domain', ['domain_name'], unique=False)
    # ### end Alembic commands ###
