"""add timezone column

Revision ID: 9a684e63e7fa
Revises: b3c8f054c636
Create Date: 2020-11-20 19:41:49.023769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a684e63e7fa'
down_revision = 'b3c8f054c636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_timezone_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'user_timezone_offset')
    # ### end Alembic commands ###
