"""remove city from event data

Revision ID: b1adcb838150
Revises: f4d14f0221ec
Create Date: 2021-05-19 20:30:22.937249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1adcb838150'
down_revision = 'f4d14f0221ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location', table_name='event')
    op.drop_constraint('fk_event_city_id', 'event', type_='foreignkey')
    op.drop_column('event', 'ip_city_id')
    op.create_index('ix_location', 'event', ['domain_id', 'ip_country_iso_code', 'timestamp'], unique=False)
    op.create_index('id_path', 'event', ['domain_id', 'path', 'timestamp'], unique=False)
    op.drop_table('city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ip_city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_event_city_id', 'event', 'city', ['ip_city_id'], ['id'])
    op.drop_index('id_path', table_name='event')
    op.drop_index('ix_location', table_name='event')
    op.create_index('ix_location', 'event', ['domain_id', 'ip_country_iso_code', 'ip_city_id', 'timestamp'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asciiname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='fk_event_country_id'),
    sa.PrimaryKeyConstraint('id', name='city_pkey')
    )
    # ### end Alembic commands ###
