"""Add referrer columns

Revision ID: b433ef4c48f1
Revises: 2b4a9f1ddb57
Create Date: 2020-12-18 21:46:51.594862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b433ef4c48f1'
down_revision = '2b4a9f1ddb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('referrer_medium', sqlalchemy_enum34.Enum('unknown', 'email', 'social', 'search'), nullable=True))
    op.add_column('event', sa.Column('referrer_name', sa.String(), nullable=True))
    op.create_index('ix_referrer', 'event', ['domain_id', 'referrer_medium', 'referrer_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referrer', table_name='event')
    op.drop_column('event', 'referrer_name')
    op.drop_column('event', 'referrer_medium')
    # ### end Alembic commands ###
