"""add stripe customer id

Revision ID: b719fb9b3588
Revises: e3844e1ac67a
Create Date: 2021-07-22 19:15:04.297900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b719fb9b3588'
down_revision = 'e3844e1ac67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_plan', sa.Enum('no_plan', 'free', 'lite', 'medium', 'enterprise', name='plan', native_enum=False), nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'active_plan')
    # ### end Alembic commands ###
