"""Restore timestamp index

Revision ID: c1a9d32b3fe8
Revises: 436ff473b7a6
Create Date: 2020-12-12 11:53:11.519080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a9d32b3fe8'
down_revision = '436ff473b7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_timestamp', 'event', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timestamp', table_name='event')
    # ### end Alembic commands ###
