"""add columns for session and page visit duration

Revision ID: c453da3a51b0
Revises: 43a06710fa6d
Create Date: 2021-08-04 22:02:48.064149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c453da3a51b0'
down_revision = '43a06710fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('seconds_since_last_visit', postgresql.INTERVAL(), nullable=True))
    op.add_column('event', sa.Column('session_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event', sa.Column('width', sa.Integer(), nullable=True))
    op.create_index('ix_seconds_since_last_visit', 'event', ['domain_id', 'seconds_since_last_visit', 'timestamp'], unique=False, postgresql_where=sa.text("seconds_since_last_visit > interval '0'"))
    op.create_index('ix_session_start', 'event', ['domain_id', 'session_start', 'timestamp'], unique=False)
    op.create_index('ix_width_height', 'event', ['domain_id', 'width', 'height', 'timestamp'], unique=False, postgresql_where=sa.text('width IS NOT NULL AND height IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_width_height', table_name='event')
    op.drop_index('ix_session_start', table_name='event')
    op.drop_index('ix_seconds_since_last_visit', table_name='event')
    op.drop_column('event', 'width')
    op.drop_column('event', 'session_start')
    op.drop_column('event', 'seconds_since_last_visit')
    op.drop_column('event', 'height')
    # ### end Alembic commands ###
