"""Add referrer columns

Revision ID: de29c6b685cc
Revises: 2b4a9f1ddb57
Create Date: 2020-12-19 16:24:35.289069

"""
from app.models.event import ReferrerMediumTypeEnum
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de29c6b685cc"
down_revision = "2b4a9f1ddb57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE referrer_medium_type AS ENUM ('unknown', 'email', 'social', 'search')"
    )
    op.add_column(
        "event",
        sa.Column(
            "referrer_medium",
            ReferrerMediumTypeEnum,
            nullable=True,
        ),
    )
    op.add_column("event", sa.Column("referrer_name", sa.String(), nullable=True))
    op.create_index(
        "ix_referrer",
        "event",
        ["domain_id", "referrer_medium", "referrer_name", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_referrer", table_name="event")
    op.drop_column("event", "referrer_name")
    op.drop_column("event", "referrer_medium")
    op.drop_table("dummytable")
    # ### end Alembic commands ###
