"""remove deprecated columns

Revision ID: e3844e1ac67a
Revises: 184d636be565
Create Date: 2021-07-14 21:27:26.715608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3844e1ac67a'
down_revision = '184d636be565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_type', table_name='event')
    op.create_index('ix_device_type', 'event', ['domain_id', 'device_type', 'timestamp'], unique=False, postgresql_where=sa.text('device_type IS NOT NULL'))
    op.drop_column('event', 'is_touch_capable')
    op.drop_column('event', 'is_pc')
    op.drop_column('event', 'is_mobile')
    op.drop_column('event', 'is_tablet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_tablet', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('is_mobile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('is_pc', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('is_touch_capable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index('ix_device_type', table_name='event')
    op.create_index('ix_device_type', 'event', ['domain_id', 'device_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###
