"""Add public column to domain

Revision ID: e55f4d11ba60
Revises: 78a6df7ee296
Create Date: 2021-02-09 19:04:52.696093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55f4d11ba60'
down_revision = '78a6df7ee296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'public')
    # ### end Alembic commands ###
