"""item -> domain, update event

Revision ID: e748644a1d21
Revises: fe521e8415a7
Create Date: 2020-05-23 21:02:09.104272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e748644a1d21'
down_revision = 'fe521e8415a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE eventtype AS ENUM {}".format(('page_view', 'custom')))

    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')

    op.add_column('event', sa.Column('event_type', postgresql.ENUM('page_view', 'custom', name='eventtype',
                                                                   create_type=False), nullable=False))
    op.add_column('event', sa.Column('load_time_ms', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('page_size_bytes', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('page_title', sa.String(), nullable=True))
    op.add_column('event', sa.Column('path', sa.String(), nullable=True))
    op.add_column('event', sa.Column('referrer', sa.String(), nullable=True))
    op.add_column('event', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('ua_string', sa.String(), nullable=True))
    op.add_column('event', sa.Column('url_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('event', sa.Column('user_timezone', sa.String(), nullable=True))
    op.drop_index('event_timestamp_idx', table_name='event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('event_timestamp_idx', 'event', ['timestamp'], unique=False)
    op.drop_column('event', 'user_timezone')
    op.drop_column('event', 'url_params')
    op.drop_column('event', 'ua_string')
    op.drop_column('event', 'status_code')
    op.drop_column('event', 'referrer')
    op.drop_column('event', 'path')
    op.drop_column('event', 'page_title')
    op.drop_column('event', 'page_size_bytes')
    op.drop_column('event', 'load_time_ms')
    op.drop_column('event', 'event_type')
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    # ### end Alembic commands ###
