"""update referrer type enum

Revision ID: f4d14f0221ec
Revises: 2ff711f69dde
Create Date: 2021-05-06 12:15:54.353491

"""
from app.models.event import ReferrerMediumType
from alembic_helpers import migrate_enum
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4d14f0221ec"
down_revision = "2ff711f69dde"
branch_labels = None
depends_on = None


new_enums = sorted(v.value for v in ReferrerMediumType)
old_enums = [v for v in new_enums if v != "internal"]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_enum(
        "event", "referrer_medium", "referrer_medium_type", old_enums, new_enums
    )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migrate_enum(
        "event", "referrer_medium", "referrer_medium_type", new_enums, old_enums
    )
    pass
    # ### end Alembic commands ###
