name: Clean up old GCR images

on:
  schedule:
    - cron: 0 8 * * 0
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install gcrgc
        run: |
          wget --quiet https://github.com/graillus/gcrgc/releases/download/v0.4.0/gcrgc_0.4.0_linux_amd64.tar.gz -O /tmp/gcrgc.tar.gz
          tar xf /tmp/gcrgc.tar.gz -C /tmp/

      - name: Cleanup images
        run: |
          ./tmp/gcrgc --exclude-tags=refs-heads-master --retention-period=14d gcr.io/${PROJECT_ID}
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
