name: Python application

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: tiangolo/docker-with-compose

    env:
      DOMAIN: backend
      SMTP_HOST: ""
      TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
      INSTALL_DEV: true
      BUILDKIT_INLINE_CACHE: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      DOCKER_IMAGE_BACKEND: europe-west4.gcr.io/no-cookie-analytics/nca-backend
      DOCKER_IMAGE_FRONTEND: europe-west4.gcr.io/no-cookie-analytics/nca-frontend

    steps:
    - uses: actions/checkout@v2

    - name: Setup env file
      run: |
        mv .env-ci .env

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create docker stack
      run: |
        docker-compose \
        -f docker-compose.yml \
        config > docker-stack.yml

    - name: Docker login
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

    - name: DEBUG
      run: |
        docker image ls

    - name: Build docker images
      run: |
        docker-compose -f docker-stack.yml build --parallel

    - name: Start docker
      run: |
        docker-compose push

    - name: Start docker
      run: |
        docker-compose -f docker-stack.yml up -d

    - name: Run tests
      run: |
        docker-compose -f docker-stack.yml exec -T backend bash /app/tests-start.sh "$@"

    - name: Log docker status
      if: ${{ always() }}
      run: |
        docker-compose logs -t
