name: Python application

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: tiangolo/docker-with-compose

    env:
      DOMAIN: backend
      SMTP_HOST: ""
      TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
      INSTALL_DEV: true
      BUILDKIT_INLINE_CACHE: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      DOCKER_IMAGE_BACKEND: docker.pkg.github.com/gaganpreet/nocookie-analytics/nca-backend
      DOCKER_IMAGE_FRONTEND: docker.pkg.github.com/gaganpreet/nocookie-analytics/nca-frontend

    steps:
    - uses: actions/checkout@v2

    - name: Setup env file
      run: |
        mv .env-ci .env

    - name: Create docker stack
      run: |
        docker-compose \
        -f docker-compose.yml \
        config > docker-stack.yml

    - name: Docker login
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

    - name: Build backend image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: gaganpreet
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: ${DOCKER_IMAGE_BACKEND}
        push_git_tag: true
        registry: docker.pkg.github.com
        context: backend

    - name: Build front-end image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: gaganpreet
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: ${DOCKER_IMAGE_FRONTEND}
        push_image_and_stages: false
        push_git_tag: true
        registry: docker.pkg.github.com
        context: frontend

    - name: DEBUG
      run: |
        docker image ls

    - name: Build docker images
      run: |
        docker-compose -f docker-stack.yml build --parallel

    - name: Start docker
      run: |
        docker-compose push

    - name: Start docker
      run: |
        docker-compose -f docker-stack.yml up -d

    - name: Run tests
      run: |
        docker-compose -f docker-stack.yml exec -T backend bash /app/tests-start.sh "$@"

    - name: Log docker status
      if: ${{ always() }}
      run: |
        docker-compose logs -t
