name: Update referers.json

on:
  schedule:
    - cron: 0 7 * * 0
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Run update script
        run: bash backend/app/data/update-referers.sh

      - name: Create Pull Request
        run: |
          git checkout -b referers-update
          git config --global user.email me@gaganpreet.in
          git config --global user.name "Gaganpreet Arora"
          if [[ $(git diff --stat backend/app/data/referers.json) ]];
          then
            git commit backend/app/data/referers.json -m "Update referers"
            git push origin referers-update
            gh pr create --title "Update referers" -B master --assignee gaganpreet -b "Update referers"
          else
            echo "Clean, nothing to do"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
